
-- This file has been automatically generated by SimUAid.

library ieee;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;
use IEEE.STD_LOGIC_ARITH.ALL;

--library SimUAid_synthesis;
--use SimUAid_synthesis.SimuAid_synthesis_pack.all;

entity SM is
port(clk, rst, x: in STD_LOGIC;

	Q1, Q2, Q3, Z: out STD_LOGIC
	);
end SM; 

architecture Structure of SM is
	signal V, Vnet_0, Q1p, W, Vnet_1, A, Vnet_2, Q3p, E, F, 
		C, D, B, K, Vnet_3, Vnet_4, SQ2, SQ1, SQ3, xp, 
		Q2p: STD_LOGIC;
		
	component nand2
        port (
                A: in STD_LOGIC;
                B: in STD_LOGIC;
                C: out STD_LOGIC
        );
    end component;
    
   component nand3
        port (
                A: in STD_LOGIC;
                B: in STD_LOGIC;
                C: in STD_LOGIC;
                D: out STD_LOGIC
        );
    end component;
	
        component inverter
    port (
            A: in STD_LOGIC;
            B: out STD_LOGIC
    );
    end component;
    

    component Dflipflop 
    port (
            CLK: in STD_LOGIC;
         D: in STD_LOGIC;
             SN: in STD_LOGIC;
            RN: in STD_LOGIC;
         Q: out STD_LOGIC;
               QN: out STD_LOGIC
    );
    end component;		
begin
	VHDL_Device_0: Dflipflop port map (clk, V, SQ1, rst, Vnet_0, Q1p);
	VHDL_Device_1: Dflipflop port map (clk, W, SQ2, rst, Vnet_1, Q2p);
	VHDL_Device_2: Dflipflop port map (clk, A, SQ3, rst, Vnet_2, Q3p);
	VHDL_Device_3: nand2 port map (E, F, V);
	VHDL_Device_4: nand2 port map (C, D, W);
	VHDL_Device_5: nand3 port map (xp, Q1p, Vnet_2, C);
	VHDL_Device_6: nand3 port map (x, Vnet_1, Q3p, D);
	VHDL_Device_7: nand3 port map (xp, B, Q1p, A);
	VHDL_Device_8: nand3 port map (xp, Vnet_1, Vnet_2, K);
	VHDL_Device_9: nand2 port map (xp, Q3p, E);
	VHDL_Device_10: nand2 port map (Vnet_0, Vnet_2, F);
	VHDL_Device_11: inverter port map (x, xp);
	VHDL_Device_12: nand2 port map (Vnet_1, Q3p, B);
	VHDL_Device_13: nand2 port map (K, K, Z);
	Q1 <= Vnet_0;
	Q2 <= Vnet_1;
	Q3 <= Vnet_2;
	SQ1 <= '1';
	SQ2 <= '1';
	SQ3 <= '1';
end Structure;